"""Vision-OCR: read text from scanned PDFs and images with the VLM.

The VLM call is stubbed (canned transcript) so these run without a GPU. PDF rasterization
uses the real pypdfium2 wheel (importorskip) on a document generated by the project's writer.
"""

from __future__ import annotations

import asyncio
import io

import pytest
from jarvis_gpt.config import ensure_runtime_dirs, load_settings
from jarvis_gpt.document_runtime import write_pdf
from jarvis_gpt.ingest import FileIngestor
from jarvis_gpt.llm import LLMResult, LLMRouter
from jarvis_gpt.storage import JarvisStorage
from jarvis_gpt.tools import ToolRegistry

# A 1x1 PNG.
_PNG_1x1 = bytes.fromhex(
    "89504e470d0a1a0a0000000d494844520000000100000001080200000090"
    "7753de0000000c4944415408d763f8cf00000001010001" + "5c" + "cdff69" + "0000000049454e44ae426082"
)


def _registry(monkeypatch, tmp_path, profile="qwen36-vl"):
    monkeypatch.setenv("JARVIS_HOME", str(tmp_path))
    monkeypatch.setenv("JARVIS_LLM_ENABLED", "0")
    monkeypatch.setenv("JARVIS_PROFILE", profile)
    settings = load_settings(profile)
    ensure_runtime_dirs(settings)
    storage = JarvisStorage(settings.database_path)
    storage.initialize()
    llm = LLMRouter(settings)
    tools = ToolRegistry(settings, storage, llm)
    return tools, storage, settings, llm


def _stub_vlm(monkeypatch, llm, text):
    async def fake_complete(messages, **kwargs):
        return LLMResult(ok=True, content=text)

    monkeypatch.setattr(llm, "complete", fake_complete)


def _upload(settings, storage, name, data):
    result = FileIngestor(settings=settings, storage=storage).ingest_upload(name, io.BytesIO(data))
    return str(result["file"]["id"])


def test_ocr_requires_vision_profile(monkeypatch, tmp_path):
    tools, storage, settings, _ = _registry(monkeypatch, tmp_path, profile="gemma4-turbo")
    file_id = _upload(settings, storage, "scan.png", _PNG_1x1)
    result = asyncio.run(tools.run("documents.ocr", {"file_id": file_id}))
    assert result.ok is False
    assert "vision" in result.summary.lower()
    storage.close()


def test_ocr_image_via_vlm(monkeypatch, tmp_path):
    tools, storage, settings, llm = _registry(monkeypatch, tmp_path)
    _stub_vlm(monkeypatch, llm, "Счёт №42 на 12345 рублей")
    file_id = _upload(settings, storage, "photo.png", _PNG_1x1)
    result = asyncio.run(tools.run("documents.ocr", {"file_id": file_id}))
    assert result.ok is True
    assert result.data["text"] == "Счёт №42 на 12345 рублей"
    assert result.data["pages"] == 1
    assert result.data["indexed"] is True
    record = storage.get_file(file_id)
    assert record["status"] == "indexed"
    assert record["chunk_count"] == 1
    assert storage.search_file_chunks("12345", limit=5)[0]["file_id"] == file_id
    provenance = storage.get_file_index_metadata(file_id)
    assert provenance["source"] == "vlm_ocr:qwen36-vl"
    assert provenance["details"] == {"pages_attempted": 1, "pages_failed": 0}
    storage.close()


def test_ocr_unsupported_type_is_rejected(monkeypatch, tmp_path):
    tools, storage, settings, llm = _registry(monkeypatch, tmp_path)
    _stub_vlm(monkeypatch, llm, "nope")
    file_id = _upload(settings, storage, "notes.txt", b"hello")
    result = asyncio.run(tools.run("documents.ocr", {"file_id": file_id}))
    assert result.ok is False
    assert "PDF" in result.summary
    storage.close()


def test_ocr_pdf_needs_pypdfium2(monkeypatch, tmp_path):
    tools, storage, settings, llm = _registry(monkeypatch, tmp_path)
    _stub_vlm(monkeypatch, llm, "x")
    monkeypatch.setattr("jarvis_gpt.tools._pypdfium2_available", lambda: False)
    pdf = tmp_path / "scan.pdf"
    write_pdf(pdf, "текст", title="t")
    file_id = _upload(settings, storage, "scan.pdf", pdf.read_bytes())
    result = asyncio.run(tools.run("documents.ocr", {"file_id": file_id}))
    assert result.ok is False
    assert "pypdfium2" in result.summary
    storage.close()


def test_ocr_pdf_rasterizes_and_reads(monkeypatch, tmp_path):
    pytest.importorskip("pypdfium2")
    tools, storage, settings, llm = _registry(monkeypatch, tmp_path)
    _stub_vlm(monkeypatch, llm, "Распознанная страница")
    pdf = tmp_path / "scan.pdf"
    write_pdf(pdf, "Привет! Это тест распознавания текста.", title="OCR тест")
    file_id = _upload(settings, storage, "scan.pdf", pdf.read_bytes())
    result = asyncio.run(tools.run("documents.ocr", {"file_id": file_id}))
    assert result.ok is True
    assert "Распознанная страница" in result.data["text"]
    assert result.data["pages"] >= 1
    storage.close()
